//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicWhereBuilder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicWhereBuilder.Resources.ValidationErrorResources", typeof(ValidationErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should provide at least one QueryPart..
        /// </summary>
        internal static string QueryPart_YouShouldProvideAtLeastOneQueryPart {
            get {
                return ResourceManager.GetString("QueryPart_YouShouldProvideAtLeastOneQueryPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should provide at least one QueryPart with a symbol..
        /// </summary>
        internal static string QueryPart_YouShouldProvideAtLeastOneQueryPartWithASymbol {
            get {
                return ResourceManager.GetString("QueryPart_YouShouldProvideAtLeastOneQueryPartWithASymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After closing parenthesis there must be logical operator or closing parenthesis..
        /// </summary>
        internal static string SequenceOfSymbols_AfterClosingParenthesisThereMustBeLogicalOperatorOrClosingParenthesis {
            get {
                return ResourceManager.GetString("SequenceOfSymbols_AfterClosingParenthesisThereMustBeLogicalOperatorOrClosingParen" +
                        "thesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After expression there must be logical operator or closing parenthesis..
        /// </summary>
        internal static string SequenceOfSymbols_AfterExpressionThereMustBeLogicalOperatorOrClosingParenthesis {
            get {
                return ResourceManager.GetString("SequenceOfSymbols_AfterExpressionThereMustBeLogicalOperatorOrClosingParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After logical operator there must be opening parenthesis or expression..
        /// </summary>
        internal static string SequenceOfSymbols_AfterLogicalOperatorThereMustBeOpeningParenthesisOrExpression {
            get {
                return ResourceManager.GetString("SequenceOfSymbols_AfterLogicalOperatorThereMustBeOpeningParenthesisOrExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After opening parenthesis there must be expression or opening parenthesis..
        /// </summary>
        internal static string SequenceOfSymbols_AfterOpeningParenthesisThereMustBeExpressionOrOpeningParenthesis {
            get {
                return ResourceManager.GetString("SequenceOfSymbols_AfterOpeningParenthesisThereMustBeExpressionOrOpeningParenthesi" +
                        "s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parenthesis mismatch.
        /// </summary>
        internal static string SequenceOfSymbols_ParenthesisMismatch {
            get {
                return ResourceManager.GetString("SequenceOfSymbols_ParenthesisMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query cannot begin with closing parenthesis..
        /// </summary>
        internal static string SequenceOfSymbols_QueryCannotBeginWithClosingParenthesis {
            get {
                return ResourceManager.GetString("SequenceOfSymbols_QueryCannotBeginWithClosingParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query cannot begin with logical operator..
        /// </summary>
        internal static string SequenceOfSymbols_QueryCannotBeginWithLogicalOperator {
            get {
                return ResourceManager.GetString("SequenceOfSymbols_QueryCannotBeginWithLogicalOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parenthesis symbol &quot;{0}&quot;..
        /// </summary>
        internal static string SequenceOfSymbols_UnknownParenthesisSymbolX {
            get {
                return ResourceManager.GetString("SequenceOfSymbols_UnknownParenthesisSymbolX", resourceCulture);
            }
        }
    }
}
